// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: sysmon.proto

/*
Package sysmonpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sysmonpb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_SysmonService_Ping_0(ctx context.Context, marshaler runtime.Marshaler, client SysmonServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq PingRequest
	var metadata runtime.ServerMetadata

	msg, err := client.Ping(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_SysmonService_Ping_0(ctx context.Context, marshaler runtime.Marshaler, server SysmonServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq PingRequest
	var metadata runtime.ServerMetadata

	msg, err := server.Ping(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterSysmonServiceHandlerServer registers the http handlers for service SysmonService to "mux".
// UnaryRPC     :call SysmonServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterSysmonServiceHandlerFromEndpoint instead.
func RegisterSysmonServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server SysmonServiceServer) error {

	mux.Handle("GET", pattern_SysmonService_Ping_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/sysmonpb.SysmonService/Ping")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_SysmonService_Ping_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SysmonService_Ping_0(ctx, mux, outboundMarshaler, w, req, response_SysmonService_Ping_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterSysmonServiceHandlerFromEndpoint is same as RegisterSysmonServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterSysmonServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterSysmonServiceHandler(ctx, mux, conn)
}

// RegisterSysmonServiceHandler registers the http handlers for service SysmonService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterSysmonServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterSysmonServiceHandlerClient(ctx, mux, NewSysmonServiceClient(conn))
}

// RegisterSysmonServiceHandlerClient registers the http handlers for service SysmonService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "SysmonServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "SysmonServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "SysmonServiceClient" to call the correct interceptors.
func RegisterSysmonServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client SysmonServiceClient) error {

	mux.Handle("GET", pattern_SysmonService_Ping_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/sysmonpb.SysmonService/Ping")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_SysmonService_Ping_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_SysmonService_Ping_0(ctx, mux, outboundMarshaler, w, req, response_SysmonService_Ping_0{resp}, mux.GetForwardResponseOptions()...)

	})

	return nil
}

type response_SysmonService_Ping_0 struct {
	proto.Message
}

func (m response_SysmonService_Ping_0) XXX_ResponseBody() interface{} {
	response := m.Message.(*PingResponse)
	return response.Body
}

var (
	pattern_SysmonService_Ping_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "ping"}, ""))
)

var (
	forward_SysmonService_Ping_0 = runtime.ForwardResponseMessage
)
