// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sysmonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SysmonServiceClient is the client API for SysmonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysmonServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type sysmonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysmonServiceClient(cc grpc.ClientConnInterface) SysmonServiceClient {
	return &sysmonServiceClient{cc}
}

func (c *sysmonServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/sysmonpb.SysmonService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysmonServiceServer is the server API for SysmonService service.
// All implementations must embed UnimplementedSysmonServiceServer
// for forward compatibility
type SysmonServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedSysmonServiceServer()
}

// UnimplementedSysmonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSysmonServiceServer struct {
}

func (UnimplementedSysmonServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSysmonServiceServer) mustEmbedUnimplementedSysmonServiceServer() {}

// UnsafeSysmonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysmonServiceServer will
// result in compilation errors.
type UnsafeSysmonServiceServer interface {
	mustEmbedUnimplementedSysmonServiceServer()
}

func RegisterSysmonServiceServer(s grpc.ServiceRegistrar, srv SysmonServiceServer) {
	s.RegisterService(&SysmonService_ServiceDesc, srv)
}

func _SysmonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysmonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysmonpb.SysmonService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysmonServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysmonService_ServiceDesc is the grpc.ServiceDesc for SysmonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysmonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysmonpb.SysmonService",
	HandlerType: (*SysmonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SysmonService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysmon.proto",
}
